name: Header/Encoding checker

on:
  push:
    branches: [ main, dev/cea ]
    paths:
      - '**.cc'
      - '**.h'
  pull_request:
    branches: [ main, dev/cea ]
    paths:
      - '**.cc'
      - '**.h'
  workflow_dispatch:

env:
  # Arcane
  ARCANE_SOURCE_DIR: '/home/runner/work/framework/framework/arcane'

jobs:
  check-headers:
    name: Check
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ env.ARCANE_SOURCE_DIR }}
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: Check files
        shell: bash
        run: |
          cd ${{ env.ARCANE_SOURCE_DIR }}
          export CC_H_FILES=$(git diff --name-only origin/main -- '*.cc' '*.h')
          chmod u+x ${{ env.ARCANE_SOURCE_DIR }}/.github/scripts/header_check.sh
          ${{ env.ARCANE_SOURCE_DIR }}/.github/scripts/header_check.sh > ${{ env.ARCANE_SOURCE_DIR }}/output.log

      - name: Display logs
        if: failure()
        shell: bash
        run: |
          cat ${{ env.ARCANE_SOURCE_DIR }}/output.log

      - name: Upload log artifact
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Header Check Log
          path: ${{ env.ARCANE_SOURCE_DIR }}/output.log
          retention-days: 7
